name : cronjob

on:
  schedule:
    - cron: '* * * * *'  # This cron expression runs the job every minute

jobs:

  Backup:
  
    runs-on: ubuntu-latest

    steps:
      - run: echo "Running backup job..."